version: '3.8'

services:

  shell:
    build: .
    command: /bin/bash
    working_dir: /app
    volumes:
      - .:/app

  hi:
    build: .
    entrypoint: coffee hi.coffee
    working_dir: /app
    volumes:
      - .:/app