version: '3.8'

services:

  shell:
    build: .
    command: /bin/bash
    working_dir: /app
    volumes:
      - .:/app

  build-hi:
    build: .
    image: cs-hi
    entrypoint: mcs hi.cs
    working_dir: /app
    volumes:
      - .:/app

  hi:
    build: .
    image: cs-hi
    entrypoint: mono hi.exe
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      build-hi:
        condition: "service_completed_successfully"