version: '3.8'

services:

  shell:
    build: .
    command: /bin/bash
    working_dir: /app
    volumes:
      - .:/app

  build-hi:
    build: .
    image: fortran-hi
    entrypoint: gfortran -ffree-form hi.f -o hi
    working_dir: /app
    volumes:
      - .:/app

  hi:
    build: .
    image: fortran-hi
    entrypoint: ./hi
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      build-hi:
        condition: "service_completed_successfully"