version: '3.8'

services:

  shell:
    build: .
    entrypoint: /bin/bash
    working_dir: /app
    volumes:
      - .:/app

  build-hi:
    build: .
    image: ocaml-hi
    entrypoint: ocamlc -o hi hi.ml
    working_dir: /app
    volumes:
      - .:/app

  hi:
    build: .
    image: ocaml-hi
    entrypoint: ./hi
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      build-hi:
        condition: "service_completed_successfully"