version: '3.8'

services:

  shell:
    build: .
    command: /bin/bash
    working_dir: /app
    volumes:
      - .:/app

  build-hi:
    build: .
    image: erlang-hi
    entrypoint: erlc hi.erl
    working_dir: /app
    volumes:
      - .:/app

  hi:
    build: .
    image: erlang-hi
    entrypoint: erl -noshell -run hi -s init stop
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      build-hi:
        condition: "service_completed_successfully"