version: '3.8'

services:

  shell:
    build: .
    entrypoint: /bin/bash
    working_dir: /app
    volumes:
      - .:/app

  hi:
    build: .
    entrypoint: lua Hi.lua
    working_dir: /app
    volumes:
      - .:/app
