version: '3.8'

services:

  shell:
    build: .
    entrypoint: /bin/bash
    working_dir: /app
    volumes:
      - .:/app

  hi:
    build: .
    entrypoint: xsltproc hi.xslt data/hi.xml
    working_dir: /app
    volumes:
      - .:/app