version: '3.8'

services:

  shell:
    build: .
    command: /bin/bash
    working_dir: /app
    volumes:
      - .:/app

  build-hi:
    build: .
    image: cobol-hi
    entrypoint: cobc -x hi.cob
    working_dir: /app
    volumes:
      - .:/app

  hi:
    build: .
    image: cobol-hi
    entrypoint: ./hi
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      build-hi:
        condition: "service_completed_successfully"

  build-fib:
    build: .
    image: cobol-fib
    entrypoint: cobc -m fibonacci.cob
    working_dir: /app/fibonacci
    volumes:
      - .:/app

  build-fib-tests:
    build: .
    image: cobol-fib
    entrypoint: cobc -x fibonacci_tests.cob fibonacci.so
    working_dir: /app/fibonacci
    volumes:
      - .:/app
    depends_on:
      build-fib:
        condition: "service_completed_successfully"

  test:
    build: .
    image: cobol-fib
    entrypoint: ./fibonacci_tests
    working_dir: /app/fibonacci
    volumes:
      - .:/app
    depends_on:
      build-fib-tests:
        condition: "service_completed_successfully"

  build-cli:
    build: .
    image: cobol-fib
    entrypoint: cobc -x cli.cob fibonacci.so
    working_dir: /app/fibonacci
    volumes:
      - .:/app
    depends_on:
      build-fib:
        condition: "service_completed_successfully"

  cli:
    build: .
    image: cobol-fib
    entrypoint: ./cli
    working_dir: /app/fibonacci
    volumes:
      - .:/app
    depends_on:
      build-cli:
        condition: "service_completed_successfully"