version: '3.8'

services:

  shell:
    build: .
    entrypoint: /bin/bash
    working_dir: /app
    volumes:
      - .:/app

  build-hi:
    build: .
    command: /root/.cargo/bin/rustc hi.rs
    working_dir: /app
    volumes:
      - .:/app

  hi:
    build: .
    entrypoint: ./hi
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      build-hi:
        condition: "service_completed_successfully"
